### ISSUE TITLE
NPE crash in version 1.3.2

### ISSUE THREAD

**Issue by simonnorberg** [telenordigital/connect-android-sdk#111]
Hi, I got this crash using version 1.3.2.

`E: FATAL EXCEPTION: main
    Process: se.telenor.mytelenor.alphatest, PID: 23883
    java.lang.NullPointerException: Attempt to invoke virtual method 'java.lang.String com.telenor.connect.WellKnownAPI$WellKnownConfig.getAnalyticsEndpoint()' on a null object reference
        at com.telenor.connect.ConnectSdk.sendAnalyticsData(ConnectSdk.java:276)
        at com.telenor.connect.ConnectSdk.access$300(ConnectSdk.java:57)
        at com.telenor.connect.ConnectSdk$3.onSuccess(ConnectSdk.java:261)
        at com.telenor.connect.id.ConnectIdService$1.success(ConnectIdService.java:97)
        at com.telenor.connect.id.ConnectIdService$1.success(ConnectIdService.java:84)
        at retrofit.CallbackRunnable$1.run(CallbackRunnable.java:45)
        at android.os.Handler.handleCallback(Handler.java:790)
        at android.os.Handler.dispatchMessage(Handler.java:99)
        at android.os.Looper.loop(Looper.java:164)
        at android.app.ActivityThread.main(ActivityThread.java:6494)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:438)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:807)`

**Comment by jorunfa** [comment]
Thanks for letting us know! Will look into it straight away.

**Comment by XarBpeak** [comment]
Still this issue occurs

Caused by java.lang.NullPointerException: Attempt to invoke virtual method 'java.lang.String com.telenor.connect.WellKnownAPI$WellKnownConfig.getAnalyticsEndpoint()' on a null object reference
       at com.telenor.connect.ConnectSdk.sendAnalyticsData(ConnectSdk.java)
       at com.telenor.connect.headerenrichment.MobileDataFetcher.fetchWebResourceResponse(MobileDataFetcher.java)
       at com.telenor.connect.headerenrichment.MobileDataFetcher.fetchUrlThroughCellular(MobileDataFetcher.java)
       at com.telenor.connect.headerenrichment.GetHeaderEnrichmentGifTask.doInBackground(GetHeaderEnrichmentGifTask.java)
       at com.telenor.connect.headerenrichment.GetHeaderEnrichmentGifTask.doInBackground(GetHeaderEnrichmentGifTask.java)
       at android.os.AsyncTask$2.call(AsyncTask.java:295)
       at java.util.concurrent.FutureTask.run(FutureTask.java:237)
       at android.os.AsyncTask$SerialExecutor$1.run(AsyncTask.java:234)
       at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1113)
       at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:588)
       at java.lang.Thread.run(Thread.java:818)
