### ISSUE TITLE
App crash Service Intent must be explicit: Intent ConnectLoginButton

### ISSUE THREAD

**Issue by Vu-Frontcell** [telenordigital/connect-android-sdk#122]
Getting crashes with following stack trace.
```
Fatal Exception: java.lang.IllegalArgumentException: Service Intent must be explicit: Intent { act=android.support.customtabs.action.CustomTabsService launchParam=MultiScreenLaunchParams { mDisplayId=0 mBaseDisplayId=0 mFlags=0 } }
       at android.app.ContextImpl.validateServiceIntent(ContextImpl.java:1391)
       at android.app.ContextImpl.bindServiceCommon(ContextImpl.java:1524)
       at android.app.ContextImpl.bindService(ContextImpl.java:1492)
       at android.content.ContextWrapper.bindService(ContextWrapper.java:711)
       at android.content.ContextWrapper.bindService(ContextWrapper.java:711)
       at android.support.customtabs.CustomTabsClient.bindCustomTabsService(CustomTabsClient.java:71)
       at com.telenor.connect.ui.ConnectLoginButton.onAttachedToWindow(ConnectLoginButton.java:156)
       at android.view.View.dispatchAttachedToWindow(View.java:16718)
       at android.view.ViewGroup.dispatchAttachedToWindow(ViewGroup.java:3158)
       at android.view.ViewGroup.dispatchAttachedToWindow(ViewGroup.java:3158)
       at android.view.ViewGroup.dispatchAttachedToWindow(ViewGroup.java:3158)
       at android.view.ViewGroup.dispatchAttachedToWindow(ViewGroup.java:3158)
       at android.view.ViewGroup.dispatchAttachedToWindow(ViewGroup.java:3158)
       at android.view.ViewGroup.dispatchAttachedToWindow(ViewGroup.java:3158)
       at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:1823)
       at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:1537)
       at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:7183)
       at android.view.Choreographer$CallbackRecord.run(Choreographer.java:959)
       at android.view.Choreographer.doCallbacks(Choreographer.java:734)
       at android.view.Choreographer.doFrame(Choreographer.java:670)
       at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:945)
       at android.os.Handler.handleCallback(Handler.java:751)
       at android.os.Handler.dispatchMessage(Handler.java:95)
       at android.os.Looper.loop(Looper.java:154)
       at android.app.ActivityThread.main(ActivityThread.java:6776)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1518)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1408)
```

**Comment by jorunfa** [comment]
This was resolved by #121, and is included in the v1.6.1 release https://github.com/telenordigital/connect-android-sdk/releases/tag/v1.6.1
