### ISSUE TITLE
Fatal Exception 

### ISSUE THREAD

**Issue by rashel007** [telenordigital/connect-android-sdk#158]
SDK version 1.9.4

`Fatal Exception: java.lang.NullPointerException: Attempt to invoke virtual method 'boolean android.support.c.e.a(android.net.Uri, android.os.Bundle, java.util.List)' on a null object reference
       at com.telenor.connect.ui.ConnectCustomTabLoginButton$1.onCustomTabsServiceConnected(Unknown Source)
       at android.support.customtabs.CustomTabsServiceConnection.onServiceConnected(Unknown Source)
       at android.app.LoadedApk$ServiceDispatcher.doConnected(LoadedApk.java:1473)
       at android.app.LoadedApk$ServiceDispatcher$RunConnection.run(LoadedApk.java:1490)
       at android.os.Handler.handleCallback(Handler.java:754)
       at android.os.Handler.dispatchMessage(Handler.java:95)
       at android.os.Looper.loop(Looper.java:163)
       at android.app.ActivityThread.main(ActivityThread.java:6342)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:880)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:770)`

**Comment by jorunfa** [comment]
Can you check if https://github.com/telenordigital/connect-android-sdk/releases/tag/v1.9.6 resolves this problem for you?

**Comment by rashel007** [comment]
It will be tough to duplicate this issue in test mode. Not all the devices or users getting this error. I will try and share. 

Another issue is happening, We have implemented SMS Retriever API.  So, when ever user requesting for otp verification from app and we are registering smsBroadcastReceiver. But when user receiving the otp sms,  connect chrome cast tab is opening and showing this message. 

![screen shot 2019-03-08 at 8 57 03 pm](https://user-images.githubusercontent.com/3868791/54036824-c1ba3400-41e6-11e9-9794-7adcb21e90c6.png)

**Comment by jorunfa** [comment]
I'm not sure what you mean when you say `We have implemented SMS Retriever API.` - SMS Retriever API is already implemented in the SDK. Are you implementing it again?

**Comment by rashel007** [comment]
We have implemented SMS Retriever API for another purpose in app. Not for Connect . But the issue is, after starting the Sms listener when user gets sms  for otp verification, connect sdk detect that and opens that page  (screenshot i shared in previous comment) . At this time user already logged in via connect.

**Comment by jorunfa** [comment]
There was a bug with leaking Broadcast Receiver, which was fixed in https://github.com/telenordigital/connect-android-sdk/releases/tag/v1.9.6.

I suspect this problem might be resolved by updating to the latest version:
https://github.com/telenordigital/connect-android-sdk/releases
it's currently this one:
https://github.com/telenordigital/connect-android-sdk/releases/tag/v1.11.3

**Comment by jorunfa** [comment]
Closing due to lack of response. Will reopen if new evidence is presented.
