### ISSUE TITLE
ConnectLoginButton InflateException

### ISSUE THREAD

**Issue by XarBpeak** [telenordigital/connect-android-sdk#166]
> android.view.InflateException
: Binary XML file line #604: Error inflating class com.telenor.connect.ui.ConnectLoginButton

where at line 604 
```
<com.telenor.connect.ui.ConnectLoginButton
                        android:id="@+id/btn_connectLogin"
                        style="?android:attr/buttonStyleSmall"
                        android:layout_width="0dp"
                        android:layout_height="wrap_content"
                        android:layout_marginLeft="10dp"
                        android:layout_marginStart="10dp"
                        android:layout_weight="5"
                        android:background="@drawable/selectable_button"
                        android:paddingLeft="5dp"
                        android:paddingRight="5dp"
                        android:visibility="gone"
                        android:text="@string/proceed"
                        android:textColor="@color/white"
                        android:textStyle="bold" />

```

**Caused by java.lang.reflect.InvocationTargetException**
      ```
 at java.lang.reflect.Constructor.constructNative(Constructor.java)
       at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
       at android.view.LayoutInflater.createView(LayoutInflater.java:594)
       at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:696)
```

**NullPointerException**
       ```
at com.telenor.connect.ui.**ConnectLoginButton.onVisibilityChanged**(ConnectLoginButton.java)
       at android.view.View.dispatchVisibilityChanged(View.java:7959)
       at android.view.ViewGroup.dispatchVisibilityChanged(ViewGroup.java:1060)
```

**Comment by SerhiiBovtriuk** [comment]
Hello, @XarBpeak. 

It's not completely clear what are you trying to do here, can you provide more information?

**Comment by XarBpeak** [comment]
This issue is only **coming in 5.1.1**   inflating ConnectLoginButton crashes.
<com.telenor.connect.ui.ConnectLoginButton

**Comment by SerhiiBovtriuk** [comment]
@XarBpeak what exactly is version 5.1.1? 

Can you, please, provide the whole error stack trace and code where the error is happening?

**Comment by XarBpeak** [comment]
5.1.1 means lollipop . Simply try on any device whose version is 5.1.1 it will occur . right now I don't have that device

**Comment by SerhiiBovtriuk** [comment]
@XarBpeak thanks for the response.

This should be fixed in next SDK release.

**Comment by SerhiiBovtriuk** [comment]
Should be solved at https://github.com/telenordigital/connect-android-sdk/pull/177
