### ISSUE TITLE
NullPointerException in getAnalyticsEndpoint() handler

### ISSUE THREAD

**Issue by SerhiiBovtriuk** [telenordigital/connect-android-sdk#173]
`Crashed: AsyncTask #1
at android.os.AsyncTask$3.done(AsyncTask.java:309)
at java.util.concurrent.FutureTask.finishCompletion(FutureTask.java:354)
at java.util.concurrent.FutureTask.setException(FutureTask.java:223)
at java.util.concurrent.FutureTask.run(FutureTask.java:242)
at android.os.AsyncTask$SerialExecutor$1.run(AsyncTask.java:234)
at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1113)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:588)
at java.lang.Thread.run(Thread.java:818)

–

Fatal Exception: java.lang.RuntimeException: An error occurred while executing doInBackground()
at android.os.AsyncTask$3.done(AsyncTask.java:309)
at java.util.concurrent.FutureTask.finishCompletion(FutureTask.java:354)
at java.util.concurrent.FutureTask.setException(FutureTask.java:223)
at java.util.concurrent.FutureTask.run(FutureTask.java:242)
at android.os.AsyncTask$SerialExecutor$1.run(AsyncTask.java:234)
at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1113)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:588)
at java.lang.Thread.run(Thread.java:818)`

**Comment by SerhiiBovtriuk** [comment]
Issue should be solved at https://github.com/telenordigital/connect-android-sdk/pull/172

**Comment by XarBpeak** [comment]
```
Fatal Exception: java.lang.RuntimeException: An error occurred while executing doInBackground()
       at android.os.AsyncTask$3.done + 309(AsyncTask.java:309)
       at java.util.concurrent.FutureTask.finishCompletion + 354(FutureTask.java:354)
       at java.util.concurrent.FutureTask.setException + 223(FutureTask.java:223)
       at java.util.concurrent.FutureTask.run + 242(FutureTask.java:242)
       at android.os.AsyncTask$SerialExecutor$1.run + 234(AsyncTask.java:234)
       at java.util.concurrent.ThreadPoolExecutor.runWorker + 1113(ThreadPoolExecutor.java:1113)
       at java.util.concurrent.ThreadPoolExecutor$Worker.run + 588(ThreadPoolExecutor.java:588)
       at java.lang.Thread.run + 818(Thread.java:818)
```

Still facing the issue using the latest connect SDK

```
Caused by java.lang.NullPointerException: Attempt to invoke virtual method 'java.lang.String com.telenor.connect.WellKnownAPI$WellKnownConfig.getAnalyticsEndpoint()' on a null object reference
       at com.telenor.connect.ConnectSdk.sendAnalyticsData(ConnectSdk.java)
```

**Comment by SerhiiBovtriuk** [comment]
Hello, @XarBpeak,
can you provide full stacktrace, please?

**Comment by SerhiiBovtriuk** [comment]
Also, @XarBpeak, 
do you have an option to reproduce this bug in your own app? We will make a fix that will stop this error from happening, but it's interesting to find the source of the problem.

**Comment by SerhiiBovtriuk** [comment]
Issue should be fixed in https://github.com/telenordigital/connect-android-sdk/pull/178
