### ISSUE TITLE
IllegalArgumentException: Unsupported ABI: null while using a webview

### ISSUE THREAD

**Issue by SerhiiBovtriuk** [telenordigital/connect-android-sdk#174]
Fatal Exception: java.lang.IllegalArgumentException: Unsupported ABI: null
at dalvik.system.VMRuntime.getInstructionSet(VMRuntime.java:324)
at dalvik.system.VMRuntime.is64BitAbi(VMRuntime.java:337)
at android.webkit.WebViewFactory.getWebViewNativeLibraryPaths(WebViewFactory.java:273)
at android.webkit.WebViewFactory.loadNativeLibrary(WebViewFactory.java:384)
at android.webkit.WebViewFactory.getProvider(WebViewFactory.java:95)
at android.webkit.CookieManager.getInstance(CookieManager.java:46)
at com.telenor.connect.id.ConnectIdService.clearCookies(ConnectIdService.java)
at com.telenor.connect.id.ConnectIdService.revokeTokens(ConnectIdService.java)
at com.telenor.connect.id.ConnectIdService$3$1.onSuccess(ConnectIdService.java)
at com.telenor.connect.id.ConnectIdService$4.onResponse(ConnectIdService.java)

**Comment by SerhiiBovtriuk** [comment]
If users are facing this error there is not much can be done. Error is caused by architecture mismatch and is user-specific. This error should appear in a very limited number of cases.

More detailed information and discussion about the bug can be found here: https://bugs.chromium.org/p/chromium/issues/detail?id=559720
