### ISSUE TITLE
InflateException: Binary XML file line #5: Error inflating class android.webkit.WebView

### ISSUE THREAD

**Issue by SerhiiBovtriuk** [telenordigital/connect-android-sdk#175]
`
Fatal Exception: java.lang.RuntimeException: Unable to start activity ComponentInfo{com.telenor.pakistan.mytelenor/com.telenor.connect.ui.ConnectActivity}: android.view.InflateException: Binary XML file line #5: Error inflating class android.webkit.WebView
at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2494)
at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2556)
at android.app.ActivityThread.access$800(ActivityThread.java:176)
at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1437)
at android.os.Handler.dispatchMessage(Handler.java:111)
at android.os.Looper.loop(Looper.java:194)
at android.app.ActivityThread.main(ActivityThread.java:5581)
at java.lang.reflect.Method.invoke(Method.java)
at java.lang.reflect.Method.invoke(Method.java:372)
at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:956)
at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:751)

Caused by android.view.InflateException: Binary XML file line #5: Error inflating class android.webkit.WebView
at android.view.LayoutInflater.createView(LayoutInflater.java:633)
at com.android.internal.policy.impl.PhoneLayoutInflater.onCreateView(PhoneLayoutInflater.java:55)
at android.view.LayoutInflater.onCreateView(LayoutInflater.java:682)
at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:741)
at android.view.LayoutInflater.rInflate(LayoutInflater.java:806)
at android.view.LayoutInflater.inflate(LayoutInflater.java:504)
at android.view.LayoutInflater.inflate(LayoutInflater.java:414)
at com.telenor.connect.ui.ConnectWebFragment.onCreateView(ConnectWebFragment.java)
at android.support.v4.app.Fragment.performCreateView(Fragment.java)
at android.support.v4.app.FragmentManagerImpl.modifiesAlpha(FragmentManagerImpl.java)
at android.support.v4.app.FragmentManagerImpl.moveFragmentToExpectedState(FragmentManagerImpl.java)
at android.support.v4.app.FragmentManagerImpl.modifiesAlpha(FragmentManagerImpl.java)
at android.support.v4.app.BackStackRecord.executeOps(BackStackRecord.java)
at android.support.v4.app.FragmentManagerImpl.executePendingTransactions(FragmentManagerImpl.java)
at android.support.v4.app.FragmentManagerImpl.modifiesAlpha(FragmentManagerImpl.java)
at android.support.v4.app.FragmentManagerImpl.executePendingTransactions(FragmentManagerImpl.java)
at android.support.v4.app.FragmentManagerImpl.removeFragment(FragmentManagerImpl.java)
at android.support.v4.app.FragmentManagerImpl.getFragments(FragmentManagerImpl.java)
at android.support.v4.app.FragmentManagerImpl.findFragmentUnder(FragmentManagerImpl.java)
at android.support.v4.app.FragmentController.dispatchActivityCreated(FragmentController.java)
at android.support.v4.app.FragmentActivity.onStart(FragmentActivity.java)
at android.app.Instrumentation.callActivityOnStart(Instrumentation.java:1228)
at android.app.Activity.performStart(Activity.java:6021)
at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2457)
at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2556)
at android.app.ActivityThread.access$800(ActivityThread.java:176)
at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1437)
at android.os.Handler.dispatchMessage(Handler.java:111)
at android.os.Looper.loop(Looper.java:194)
at android.app.ActivityThread.main(ActivityThread.java:5581)
at java.lang.reflect.Method.invoke(Method.java)
at java.lang.reflect.Method.invoke(Method.java:372)
at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:956)
at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:751)`

**Comment by SerhiiBovtriuk** [comment]
This most likely look like an OS problem and nothing to do with an SDK. Additional request sent to the developers to clarify the severity of the bug.

**Comment by SerhiiBovtriuk** [comment]
The reason for this is knows issues with ABI: null.

More information here: https://bugs.chromium.org/p/chromium/issues/detail?id=559720

Looks like it cannot be fixed on the sdk side.
